### ISSUE TITLE
About configure file

### ISSUE THREAD

**Issue by lhanzhang123** [ysshao/ALADDIN#26]
Problem 1 : pipeline did not affect the result and aladdin result show that loop pipelining always be not ON .
Problem 2 : power model just can working on 10ns cycle time , did not supports other ?

THANKYOU

**Comment by xyzsam** [comment]
Are you using the global pipelining directive (`pipelining,1`) or the per-loop pipelining directive (`pipeline,function_name,loop_name`)? We recommend the latter, as it is more reliable. If aladdin prints that pipelining is not ON, and you've used the second option, you can ignore that warning. Otherwise, are you sure your code can take advantage of loop pipelining? What are you running?

Regarding the power model: we support cycle time 1,2,3,4,5,6, and 10 (https://github.com/ysshao/ALADDIN/blob/master/common/power_func.cpp#L8).

**Comment by lhanzhang123** [comment]
i'm using per-loop pipelining directive in the triad , but did not have any effect . 
i'm trying to use 1ns , but the aladdin's result show that  Current power model supports trig functions running at 10 ns.  Cycle time: 1 is not supported yet. Use 10ns power model instead.

this is my configure file :
partition,cyclic,a,8192,4,2
partition,cyclic,b,8192,4,2
partition,cyclic,c,8192,4,2
unrolling,triad,triad,2
pipeline,triad,1
cycle_time,1

thank for reply .
